sudo: required

language: ruby

env:
  - PROJECT_ID="mysocialapp" CASSANDRA_VERSION="3.11.1" VERSION=${CASSANDRA_VERSION}-7 CASSANDRA_SHA="6feed696759e2f3219e0ebde13f4c9080cac0744a77eb3cb43af136ab527f0ed" DEV_CONTAINER=yes

services:
  - docker

before_install:
  - git submodule update --init

script:
  - echo "[+] Building Cassandra image"
  - sed -i "s/CASSANDRA_RELEASE=.*/CASSANDRA_RELEASE=${CASSANDRA_VERSION} \\\/" docker-cassandra-k8s/Dockerfile
  - sed -i "s/CASSANDRA_SHA=.*/CASSANDRA_SHA=${CASSANDRA_SHA} \\\/" docker-cassandra-k8s/Dockerfile
  - echo -e "[cql]\nversion = 3.4.4\n\n[connection]\nrequest_timeout = 300" > docker-cassandra-k8s/files/cqlshrc
  - echo -e "#!/bin/bash\ncd /usr/local/apache-cassandra/bin/\n./nodetool" > docker-cassandra-k8s/files/nodetool.sh
  - sed -i "s/jq \\\/jq \\\ \n    \&\& apt-get -y install python-pip dh-autoreconf \\\ \n    \&\& pip install cqlsh \\\ \n  \&\&   mkdir \/root\/.cassandra \&\& mv \/cqlshrc \/root\/.cassandra\/ \&\& chmod 755 \/nodetool.sh \&\& mv \/nodetool.sh \/usr\/bin\/nodetool \\\/" docker-cassandra-k8s/Dockerfile
  - sed -i "s/ --squash//g" docker-cassandra-k8s/Makefile
  - cd docker-cassandra-k8s && make docker && cd ..
  - echo "[+] Building Cassandra backup image"
  - sed -i "s/IMAGE_FROM_VERSION/${VERSION}/g" Dockerfile
  - docker build -t quay.io/${PROJECT_ID}/cassandra-backup:${VERSION} .

after_success:
  - test $(curl -s https://quay.io/api/v1/repository/$PROJECT_ID/cassandra/tag/ | jq ".tags[] | select(.name == \"$VERSION\") | select(.end_ts == null) | .name" | wc -l) -eq 0 || echo "Container tag $VERSION already exist, cancelling push to avoid override"
  - docker login -u="$QUAY_USERNAME" -p="$QUAY_PASSWORD" quay.io
  - echo "Pushing Cassandra image"
  - cd docker-cassandra-k8s && make push && cd ..
  - echo "Pushing Cassandra backup image"
  - docker push quay.io/${PROJECT_ID}/cassandra-backup:${VERSION}

